// SPDX-License-Identifier: MIT
pragma solidity ^0.8.4;

interface IVault {
    function addressBook (  ) external view returns ( address );
    function claim (  ) external returns ( bool );
    function claimCooldown (  ) external view returns ( uint256 );
    function claims ( address, uint256 ) external view returns ( uint256 );
    function compound (  ) external returns ( bool );
    function deposit ( uint256 quantity_, address referrer_ ) external returns ( bool );
    function deposit ( uint256 quantity_ ) external returns ( bool );
    function depositFor ( address player_, uint256 quantity_ ) external returns ( bool );
    function depositFor ( address player_, uint256 quantity_, address referrer_ ) external returns ( bool );
    function effectiveClaims ( address player_ ) external returns ( uint256 );
    function initialDeposit ( address ) external view returns ( uint256 );
    function initialize (  ) external;
    function lastAction ( address ) external view returns ( uint256 );
    function lastClaim ( address ) external view returns ( uint256 );
    function lastDeposit ( address ) external view returns ( uint256 );
    function lookback (  ) external view returns ( uint256 );
    function maxPayout (  ) external view returns ( uint256 );
    function maxReturn (  ) external view returns ( uint256 );
    function maxThreshold (  ) external view returns ( uint256 );
    function maxed ( address ) external view returns ( bool );
    function maxedPercent ( address ) external view returns ( uint256 );
    function negative ( address ) external view returns ( bool );
    function negativeClaims (  ) external view returns ( uint256 );
    function neutralClaims (  ) external view returns ( uint256 );
    function owner (  ) external view returns ( address );
    function pause (  ) external;
    function paused (  ) external view returns ( bool );
    function penalized ( address ) external view returns ( bool );
    function penaltyClaims (  ) external view returns ( uint256 );
    function penaltyLookback (  ) external view returns ( uint256 );
    function penaltyRate (  ) external view returns ( uint256 );
    function period (  ) external view returns ( uint256 );
    function proxiableUUID (  ) external view returns ( bytes32 );
    function rates ( uint256 ) external view returns ( uint256 );
    function referrals ( address, uint256 ) external view returns ( address );
    function referrer ( address ) external view returns ( address );
    function renounceOwnership (  ) external;
    function rewardAvailable ( address player_ ) external returns ( uint256 );
    function rewardPercent ( address player_ ) external returns ( uint256 );
    function setAddressBook ( address address_ ) external;
    function startTime ( address ) external view returns ( uint256 );
    function totalClaim ( address ) external view returns ( uint256 );
    function totalDeposit ( address ) external view returns ( uint256 );
    function transferOwnership ( address newOwner ) external;
    function unpause (  ) external;
    function upgradeTo ( address newImplementation ) external;
    function upgradeToAndCall ( address newImplementation, bytes memory data ) external;
}
